## function
mypack <- function(package){
  new.package <- package[!(package %in% installed.packages()[, "Package"])]
  if (length(new.package)) 
    install.packages(new.package, dependencies = TRUE)
  sapply(package, require, character.only = TRUE)
}

## usage
packages <- c("dplyr", "tidyr", "readr", "stringr", "broom", "purrr", "readr", "reshape2", "lubridate", 
              "rvest", "plyr", "ggvis", "knitr", 
              "RColorBrewer", "scales", "grid", "rmarkdown", "shiny", "swirl",
              "DBI", "httr", "rticles",
              "tm", "wordcloud", "openNLP", "gutenbergr", "tidytext",
              "twitteR", "RCurl", "RJSONIO", "ROAuth",
              "DT", "sqldf", "data.table", "RODBC", "RPostgreSQL", "RSQLite", 
              "XLConnect", "xlsx", "Rcpp", "XML", "jsonlite",
              "fivethirtyeight", "plotly", "highcharter", "leaflet", "threejs",
              "ggplot2", "ggrepel", "ggvis", "rgl", "googleVis", 
              "sp", "maptools", "rgdal", "maps", "ggmap", "countrycode", "viridisLite",
              "zoo", "xts", "dygraphs", "leaps", "glmnet", "caTools", "gbm",
              "car","lme4", "randomForest", "multcomp", "vcd", "glmnet", "caret", "caretEnsemble", "pROC",
              "prophet")

mypack(packages)

####################

# install h2o
## The following two commands remove any previously installed H2O packages for R.
if ("package:h2o" %in% search()) { detach("package:h2o", unload=TRUE) }
if ("h2o" %in% rownames(installed.packages())) { remove.packages("h2o") }

## Next, we download packages that H2O depends on.
if (! ("methods" %in% rownames(installed.packages()))) { install.packages("methods") }
if (! ("statmod" %in% rownames(installed.packages()))) { install.packages("statmod") }
if (! ("stats" %in% rownames(installed.packages()))) { install.packages("stats") }
if (! ("graphics" %in% rownames(installed.packages()))) { install.packages("graphics") }
if (! ("RCurl" %in% rownames(installed.packages()))) { install.packages("RCurl") }
if (! ("jsonlite" %in% rownames(installed.packages()))) { install.packages("jsonlite") }
if (! ("tools" %in% rownames(installed.packages()))) { install.packages("tools") }
if (! ("utils" %in% rownames(installed.packages()))) { install.packages("utils") }

## Now we download, install and initialize the H2O package for R.
install.packages("h2o", type="source", repos=(c("http://h2o-release.s3.amazonaws.com/h2o/rel-ueno/6/R")))
library(h2o)
localH2O = h2o.init(nthreads=-1)

## Finally, let's run a demo to see H2O at work.
demo(h2o.kmeans)
